language: go
go:
- 1.13.x
- 1.12.x
- 1.11.x
  env: GO111MODULE=off
install:
- go get -t ./...
- if [[ "$TRAVIS_GO_VERSION" =~ ^1\.13\. ]]; then ./scripts/install-checks.sh; fi
before_script:
- if [[ "$TRAVIS_GO_VERSION" =~ ^1\.13\. ]]; then ./scripts/check.sh; fi
- go build
- go build $(go list ./examples/...)
script:
- if [[ "$TRAVIS_GO_VERSION" =~ ^1\.13\. ]]; then ./scripts/cover.sh TRAVIS; else go test -i -race ./...; fi
