language: go
go:
- 1.11.x
- 1.12.x
- 1.13.x
install:
- go get -t ./...
- go get github.com/mattn/goveralls
- go get golang.org/x/lint/golint
- go get github.com/client9/misspell/cmd/misspell
before_script:
- if [[ "$TRAVIS_GO_VERSION" =~ ^1\.13\. ]]; then ./scripts/lint.sh; fi
- go build $(go list ./examples/...)
script:
- if [[ "$TRAVIS_GO_VERSION" =~ ^1\.13\. ]]; then ./scripts/cover.sh TRAVIS; else go test -i -race ./...; fi
