language: go
go:
- 1.10.x
- 1.11.x
- 1.12.x
install:
- go get -t ./...
- go get github.com/mattn/goveralls
- go get golang.org/x/lint/golint
- go get github.com/client9/misspell/cmd/misspell
before_script:
- $(exit $(go fmt ./... | wc -l))
- go vet ./...
- golint ./...
- misspell -error -locale US ./...
script:
- go test -i -race ./...
- if [[ "$TRAVIS_GO_VERSION" =~ ^1\.12\. ]]; then ./scripts/cover.sh TRAVIS; else go test -race ./...; fi
